# Generated by Django 5.2.6 on 2026-09-22 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodigoAcesso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "codigo_hash",
                    models.CharField(max_length=128, verbose_name="codigo (hash)"),
                ),
                ("expira_em", models.DateTimeField(verbose_name="expira em")),
                (
                    "tentativas",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="tentativas"
                    ),
                ),
                (
                    "usado_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="usado em"
                    ),
                ),
                (
                    "canal",
                    models.CharField(
                        default="email", max_length=20, verbose_name="canal de envio"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="codigos_acesso",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "codigo de acesso",
                "verbose_name_plural": "codigos de acesso",
                "ordering": ["-criado_em"],
            },
        ),
    ]
