# Generated by Django 5.2.6 on 2026-09-22 19:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crm", "0002_lead_urgencia"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Diagnostico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="identificador publico",
                    ),
                ),
                (
                    "nome",
                    models.CharField(blank=True, max_length=150, verbose_name="nome"),
                ),
                (
                    "empresa",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="empresa"
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="telefone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="e-mail"
                    ),
                ),
                ("respostas", models.JSONField(default=list, verbose_name="respostas")),
                (
                    "pontuacao",
                    models.PositiveIntegerField(default=0, verbose_name="pontuacao"),
                ),
                (
                    "urgencia",
                    models.CharField(
                        choices=[
                            ("ALTA", "Urgencia alta"),
                            ("MEDIA", "Urgencia media"),
                            ("BAIXA", "Urgencia baixa"),
                            ("PF", "Divida apenas pessoal"),
                        ],
                        max_length=5,
                        verbose_name="urgencia",
                    ),
                ),
                (
                    "atendido_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="primeiro contato em"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="observacoes"),
                ),
                (
                    "atendido_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="diagnosticos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="atendido por",
                    ),
                ),
                (
                    "lead",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="diagnostico",
                        to="crm.lead",
                        verbose_name="lead gerado",
                    ),
                ),
            ],
            options={
                "verbose_name": "diagnostico",
                "verbose_name_plural": "diagnosticos",
                "ordering": ["-criado_em"],
            },
        ),
    ]
