# Generated by Django 5.2.6 on 2026-09-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publico", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diagnostico",
            name="urgencia",
            field=models.CharField(
                choices=[
                    ("ALTA", "Urgência alta"),
                    ("MEDIA", "Urgência média"),
                    ("BAIXA", "Urgência baixa"),
                    ("PF", "Dívida apenas pessoal"),
                ],
                max_length=5,
                verbose_name="urgencia",
            ),
        ),
    ]
