# Generated by Django 5.2.6 on 2026-09-22 14:33

import apps.core.validators
import apps.processos.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("empresas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessoRJ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "numero_cnj",
                    models.CharField(
                        max_length=25,
                        unique=True,
                        validators=[apps.core.validators.validar_numero_cnj],
                        verbose_name="numero CNJ",
                    ),
                ),
                (
                    "tribunal",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="tribunal"
                    ),
                ),
                (
                    "comarca",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="comarca"
                    ),
                ),
                (
                    "vara",
                    models.CharField(blank=True, max_length=120, verbose_name="vara"),
                ),
                (
                    "juiz",
                    models.CharField(blank=True, max_length=150, verbose_name="juiz"),
                ),
                (
                    "administrador_judicial",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="administrador judicial",
                    ),
                ),
                (
                    "aj_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="e-mail do AJ"
                    ),
                ),
                (
                    "aj_telefone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="telefone do AJ"
                    ),
                ),
                (
                    "advogado",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="advogado responsavel"
                    ),
                ),
                (
                    "fase",
                    models.CharField(
                        choices=[
                            ("PRE", "Pre-ajuizamento"),
                            ("DIST", "Distribuido"),
                            ("DEFER", "Processamento deferido (art. 52)"),
                            ("PLANO", "Plano apresentado (art. 53)"),
                            ("EDITAL", "Edital publicado / habilitacoes"),
                            ("OBJ", "Prazo de objecoes"),
                            ("AGC", "Assembleia de credores"),
                            ("CONC", "RJ concedida (art. 58)"),
                            ("FISC", "Periodo de fiscalizacao (art. 61)"),
                            ("ENC", "Encerrada (art. 63)"),
                            ("FAL", "Convolada em falencia"),
                        ],
                        default="DIST",
                        max_length=6,
                        verbose_name="fase atual",
                    ),
                ),
                (
                    "data_distribuicao",
                    models.DateField(
                        blank=True, null=True, verbose_name="distribuicao"
                    ),
                ),
                (
                    "data_deferimento",
                    models.DateField(
                        blank=True,
                        help_text="Art. 52. Marco inicial do stay period e do prazo do plano.",
                        null=True,
                        verbose_name="deferimento do processamento",
                    ),
                ),
                (
                    "data_edital_52",
                    models.DateField(
                        blank=True,
                        help_text="Abre o prazo de 15 dias para habilitacoes e divergencias.",
                        null=True,
                        verbose_name="publicacao do edital (art. 52, §1)",
                    ),
                ),
                (
                    "data_plano",
                    models.DateField(
                        blank=True, null=True, verbose_name="apresentacao do plano"
                    ),
                ),
                (
                    "data_edital_53",
                    models.DateField(
                        blank=True,
                        help_text="Abre o prazo de 30 dias para objecoes dos credores.",
                        null=True,
                        verbose_name="publicacao do aviso do plano (art. 53)",
                    ),
                ),
                (
                    "data_agc",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="assembleia geral de credores",
                    ),
                ),
                (
                    "data_concessao",
                    models.DateField(
                        blank=True, null=True, verbose_name="concessao da RJ (art. 58)"
                    ),
                ),
                (
                    "encerrado_em",
                    models.DateField(
                        blank=True, null=True, verbose_name="encerramento (art. 63)"
                    ),
                ),
                (
                    "stay_prorrogado",
                    models.BooleanField(
                        default=False,
                        help_text="Art. 6, §4: prorrogacao por igual periodo, uma unica vez.",
                        verbose_name="stay period prorrogado",
                    ),
                ),
                (
                    "valor_divida",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="valor total sujeito a RJ",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="observacoes"),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processos",
                        to="empresas.empresa",
                        verbose_name="empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "processo de RJ",
                "verbose_name_plural": "processos de RJ",
                "ordering": ["-data_distribuicao", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Prazo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="titulo")),
                (
                    "base_legal",
                    models.CharField(
                        blank=True,
                        help_text="Ex.: Lei 11.101/2005, art. 53.",
                        max_length=120,
                        verbose_name="base legal",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("LEGAL", "Prazo legal"),
                            ("JUD", "Prazo judicial"),
                            ("INT", "Controle interno"),
                        ],
                        default="LEGAL",
                        max_length=5,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "data_inicio",
                    models.DateField(blank=True, null=True, verbose_name="inicio"),
                ),
                ("data_fim", models.DateField(verbose_name="vencimento")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PEND", "Pendente"),
                            ("CUMP", "Cumprido"),
                            ("PROR", "Prorrogado"),
                            ("PERD", "Perdido"),
                        ],
                        default="PEND",
                        max_length=4,
                        verbose_name="status",
                    ),
                ),
                (
                    "concluido_em",
                    models.DateField(
                        blank=True, null=True, verbose_name="concluido em"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="observacoes"),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prazos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="responsavel",
                    ),
                ),
                (
                    "processo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prazos",
                        to="processos.processorj",
                        verbose_name="processo",
                    ),
                ),
            ],
            options={
                "verbose_name": "prazo",
                "verbose_name_plural": "prazos",
                "ordering": ["data_fim"],
            },
        ),
        migrations.CreateModel(
            name="Parcela",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "classe",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("I", "Classe I - trabalhista"),
                            ("II", "Classe II - garantia real"),
                            ("III", "Classe III - quirografario"),
                            ("IV", "Classe IV - ME/EPP"),
                        ],
                        max_length=3,
                        verbose_name="classe",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=200, verbose_name="descricao"),
                ),
                ("vencimento", models.DateField(verbose_name="vencimento")),
                (
                    "valor_previsto",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="valor previsto"
                    ),
                ),
                (
                    "valor_pago",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="valor pago",
                    ),
                ),
                (
                    "pago_em",
                    models.DateField(blank=True, null=True, verbose_name="pago em"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PREV", "Prevista"),
                            ("PAGA", "Paga"),
                            ("ATRA", "Em atraso"),
                            ("RENE", "Renegociada"),
                        ],
                        default="PREV",
                        max_length=4,
                        verbose_name="status",
                    ),
                ),
                (
                    "processo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parcelas",
                        to="processos.processorj",
                        verbose_name="processo",
                    ),
                ),
            ],
            options={
                "verbose_name": "parcela do plano",
                "verbose_name_plural": "parcelas do plano",
                "ordering": ["vencimento"],
            },
        ),
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="titulo")),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("PLANO", "Plano de recuperacao"),
                            ("LAUDO", "Laudo economico-financeiro"),
                            ("BALANCO", "Demonstracoes contabeis"),
                            ("EDITAL", "Edital"),
                            ("ATA", "Ata de assembleia"),
                            ("PET", "Peticao"),
                            ("DEC", "Decisao / sentenca"),
                            ("REL", "Relatorio mensal de atividades"),
                            ("CERT", "Certidao"),
                            ("CONTR", "Contrato"),
                            ("OUT", "Outro"),
                        ],
                        default="OUT",
                        max_length=8,
                        verbose_name="categoria",
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        upload_to=apps.processos.models.caminho_documento,
                        verbose_name="arquivo",
                    ),
                ),
                (
                    "data_referencia",
                    models.DateField(
                        blank=True, null=True, verbose_name="data de referencia"
                    ),
                ),
                (
                    "visivel_cliente",
                    models.BooleanField(
                        default=True, verbose_name="visivel no portal do cliente"
                    ),
                ),
                (
                    "enviado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documentos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="enviado por",
                    ),
                ),
                (
                    "processo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="processos.processorj",
                        verbose_name="processo",
                    ),
                ),
            ],
            options={
                "verbose_name": "documento",
                "verbose_name_plural": "documentos",
                "ordering": ["-data_referencia", "-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="Credor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                ("nome", models.CharField(max_length=200, verbose_name="credor")),
                (
                    "documento",
                    models.CharField(
                        blank=True, max_length=18, verbose_name="CPF/CNPJ"
                    ),
                ),
                (
                    "classe",
                    models.CharField(
                        choices=[
                            ("I", "Classe I - trabalhista"),
                            ("II", "Classe II - garantia real"),
                            ("III", "Classe III - quirografario"),
                            ("IV", "Classe IV - ME/EPP"),
                        ],
                        max_length=3,
                        verbose_name="classe",
                    ),
                ),
                (
                    "valor_arrolado",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="valor arrolado",
                    ),
                ),
                (
                    "valor_habilitado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="valor habilitado",
                    ),
                ),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("ARR", "Arrolado pela devedora"),
                            ("HAB", "Habilitado"),
                            ("DIV", "Divergencia apresentada"),
                            ("IMP", "Impugnado"),
                            ("EXC", "Excluido"),
                        ],
                        default="ARR",
                        max_length=3,
                        verbose_name="situacao",
                    ),
                ),
                (
                    "sujeito_rj",
                    models.BooleanField(default=True, verbose_name="sujeito a RJ"),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="observacoes"),
                ),
                (
                    "processo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credores",
                        to="processos.processorj",
                        verbose_name="processo",
                    ),
                ),
            ],
            options={
                "verbose_name": "credor",
                "verbose_name_plural": "credores",
                "ordering": ["classe", "-valor_arrolado"],
            },
        ),
        migrations.CreateModel(
            name="Andamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "data",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="data"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("MOV", "Movimentacao"),
                            ("PET", "Peticao"),
                            ("DEC", "Decisao"),
                            ("DESP", "Despacho"),
                            ("SENT", "Sentenca"),
                            ("AUD", "Audiencia"),
                            ("AGC", "Assembleia de credores"),
                            ("RAJ", "Relatorio do administrador judicial"),
                            ("OUT", "Outro"),
                        ],
                        default="MOV",
                        max_length=5,
                        verbose_name="tipo",
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="titulo")),
                ("descricao", models.TextField(blank=True, verbose_name="descricao")),
                (
                    "fonte",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Lancamento manual"),
                            ("TRIBUNAL", "Integracao com o tribunal"),
                            ("IMPORT", "Importacao de arquivo"),
                        ],
                        default="MANUAL",
                        max_length=10,
                        verbose_name="fonte",
                    ),
                ),
                (
                    "visivel_cliente",
                    models.BooleanField(
                        default=True,
                        help_text="Desmarque para manter o andamento restrito a equipe interna.",
                        verbose_name="visivel no portal do cliente",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="andamentos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="registrado por",
                    ),
                ),
                (
                    "processo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="andamentos",
                        to="processos.processorj",
                        verbose_name="processo",
                    ),
                ),
            ],
            options={
                "verbose_name": "andamento",
                "verbose_name_plural": "andamentos",
                "ordering": ["-data", "-id"],
            },
        ),
    ]
