# Generated by Django 5.2.6 on 2026-09-22 14:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="andamento",
            name="codigo_movimento",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="codigo do movimento (CNJ)"
            ),
        ),
        migrations.AddField(
            model_name="andamento",
            name="id_externo",
            field=models.CharField(
                blank=True,
                help_text="Preenchido pela integracao com o tribunal para evitar duplicidade.",
                max_length=64,
                verbose_name="identificador na origem",
            ),
        ),
        migrations.AddField(
            model_name="processorj",
            name="datajud_alias",
            field=models.CharField(
                blank=True,
                help_text="Use apenas se a sigla do tribunal acima nao for a do indice do CNJ (ex.: TJSP, TRT15, TRF3).",
                max_length=20,
                verbose_name="sigla no DataJud",
            ),
        ),
        migrations.AddConstraint(
            model_name="andamento",
            constraint=models.UniqueConstraint(
                condition=models.Q(("id_externo", ""), _negated=True),
                fields=("processo", "id_externo"),
                name="andamento_unico_por_origem",
            ),
        ),
    ]
