# Generated by Django 5.2.6 on 2026-09-22 16:51

import apps.processos.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processos", "0002_andamento_codigo_movimento_andamento_id_externo_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportacaoCredores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "arquivo",
                    models.FileField(
                        upload_to=apps.processos.models.caminho_importacao,
                        verbose_name="arquivo",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PEND", "Aguardando conferencia"),
                            ("CONC", "Concluida"),
                            ("CANC", "Cancelada"),
                        ],
                        default="PEND",
                        max_length=4,
                        verbose_name="status",
                    ),
                ),
                (
                    "linhas_lidas",
                    models.PositiveIntegerField(default=0, verbose_name="linhas lidas"),
                ),
                (
                    "linhas_validas",
                    models.PositiveIntegerField(
                        default=0, verbose_name="linhas validas"
                    ),
                ),
                (
                    "criados",
                    models.PositiveIntegerField(
                        default=0, verbose_name="credores criados"
                    ),
                ),
                (
                    "atualizados",
                    models.PositiveIntegerField(
                        default=0, verbose_name="credores atualizados"
                    ),
                ),
                (
                    "ignorados",
                    models.PositiveIntegerField(
                        default=0, verbose_name="linhas ignoradas"
                    ),
                ),
                ("mensagem", models.TextField(blank=True, verbose_name="mensagem")),
                (
                    "enviado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="importacoes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="enviado por",
                    ),
                ),
                (
                    "processo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="importacoes",
                        to="processos.processorj",
                        verbose_name="processo",
                    ),
                ),
            ],
            options={
                "verbose_name": "importacao de credores",
                "verbose_name_plural": "importacoes de credores",
                "ordering": ["-criado_em"],
            },
        ),
    ]
