# Generated by Django 5.2.6 on 2026-09-22 19:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processos", "0003_importacaocredores"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="credor",
            name="estagio_negociacao",
            field=models.CharField(
                choices=[
                    ("NAO", "Nao iniciada"),
                    ("LEV", "Levantamento"),
                    ("NEG", "Em negociacao"),
                    ("PROP", "Proposta enviada"),
                    ("ACOR", "Acordo fechado"),
                    ("JUD", "Discussao judicial"),
                ],
                default="NAO",
                max_length=5,
                verbose_name="estagio da negociacao",
            ),
        ),
        migrations.AddField(
            model_name="credor",
            name="valor_negociado",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Deixe vazio enquanto nao houver proposta fechada.",
                max_digits=15,
                null=True,
                verbose_name="valor apos negociacao",
            ),
        ),
        migrations.AddField(
            model_name="credor",
            name="visivel_cliente",
            field=models.BooleanField(default=True, verbose_name="visivel no portal"),
        ),
        migrations.CreateModel(
            name="EventoNegociacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "data",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="data"
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=250, verbose_name="o que aconteceu"),
                ),
                (
                    "visivel_cliente",
                    models.BooleanField(default=True, verbose_name="visivel no portal"),
                ),
                (
                    "credor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventos",
                        to="processos.credor",
                        verbose_name="credor",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="eventos_negociacao",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="registrado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "evento da negociacao",
                "verbose_name_plural": "eventos da negociacao",
                "ordering": ["-data", "-id"],
            },
        ),
    ]
