# Generated by Django 5.2.6 on 2026-09-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processos", "0004_credor_estagio_negociacao_credor_valor_negociado_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credor",
            name="estagio_negociacao",
            field=models.CharField(
                choices=[
                    ("NAO", "Não iniciada"),
                    ("LEV", "Levantamento"),
                    ("NEG", "Em negociação"),
                    ("PROP", "Proposta enviada"),
                    ("ACOR", "Acordo fechado"),
                    ("JUD", "Discussão judicial"),
                ],
                default="NAO",
                max_length=5,
                verbose_name="estagio da negociacao",
            ),
        ),
    ]
