# Generated by Django 5.2.6 on 2026-09-22 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("processos", "0002_andamento_codigo_movimento_andamento_id_externo_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SincronizacaoDataJud",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "executado_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="executado em"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OK", "Concluida"),
                            ("VAZIO", "Processo nao encontrado no tribunal"),
                            ("ERRO", "Erro"),
                        ],
                        max_length=5,
                        verbose_name="status",
                    ),
                ),
                (
                    "movimentos_recebidos",
                    models.PositiveIntegerField(
                        default=0, verbose_name="movimentos recebidos"
                    ),
                ),
                (
                    "andamentos_criados",
                    models.PositiveIntegerField(
                        default=0, verbose_name="andamentos criados"
                    ),
                ),
                ("mensagem", models.TextField(blank=True, verbose_name="mensagem")),
                (
                    "executado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sincronizacoes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="executado por",
                    ),
                ),
                (
                    "processo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sincronizacoes",
                        to="processos.processorj",
                        verbose_name="processo",
                    ),
                ),
            ],
            options={
                "verbose_name": "sincronizacao com o DataJud",
                "verbose_name_plural": "sincronizacoes com o DataJud",
                "ordering": ["-executado_em"],
            },
        ),
    ]
