# Generated by Django 5.2.6 on 2026-09-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integracoes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sincronizacaodatajud",
            name="atualizado_no_tribunal_em",
            field=models.CharField(
                blank=True,
                help_text="Campo dataHoraUltimaAtualizacao devolvido pelo Datajud.",
                max_length=40,
                verbose_name="ultima atualizacao no tribunal",
            ),
        ),
    ]
