# Generated by Django 5.2.6 on 2026-09-22 14:33

import apps.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "razao_social",
                    models.CharField(max_length=200, verbose_name="razao social"),
                ),
                (
                    "nome_fantasia",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="nome fantasia"
                    ),
                ),
                (
                    "cnpj",
                    models.CharField(
                        max_length=18,
                        unique=True,
                        validators=[apps.core.validators.validar_cnpj],
                        verbose_name="CNPJ",
                    ),
                ),
                (
                    "porte",
                    models.CharField(
                        choices=[
                            ("MEI", "MEI"),
                            ("ME", "Microempresa"),
                            ("EPP", "Empresa de pequeno porte"),
                            ("MEDIA", "Media empresa"),
                            ("GRANDE", "Grande empresa"),
                        ],
                        default="EPP",
                        max_length=10,
                        verbose_name="porte",
                    ),
                ),
                (
                    "atividade",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="atividade principal"
                    ),
                ),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("PROSPECT", "Prospect"),
                            ("CLIENTE", "Cliente ativo"),
                            ("SUSPENSO", "Contrato suspenso"),
                            ("ENCERRADO", "Contrato encerrado"),
                        ],
                        default="CLIENTE",
                        max_length=10,
                        verbose_name="situacao",
                    ),
                ),
                ("cep", models.CharField(blank=True, max_length=9, verbose_name="CEP")),
                (
                    "logradouro",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="logradouro"
                    ),
                ),
                (
                    "numero",
                    models.CharField(blank=True, max_length=20, verbose_name="numero"),
                ),
                (
                    "complemento",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="complemento"
                    ),
                ),
                (
                    "bairro",
                    models.CharField(blank=True, max_length=100, verbose_name="bairro"),
                ),
                (
                    "cidade",
                    models.CharField(blank=True, max_length=100, verbose_name="cidade"),
                ),
                (
                    "uf",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AC", "AC"),
                            ("AL", "AL"),
                            ("AP", "AP"),
                            ("AM", "AM"),
                            ("BA", "BA"),
                            ("CE", "CE"),
                            ("DF", "DF"),
                            ("ES", "ES"),
                            ("GO", "GO"),
                            ("MA", "MA"),
                            ("MT", "MT"),
                            ("MS", "MS"),
                            ("MG", "MG"),
                            ("PA", "PA"),
                            ("PB", "PB"),
                            ("PR", "PR"),
                            ("PE", "PE"),
                            ("PI", "PI"),
                            ("RJ", "RJ"),
                            ("RN", "RN"),
                            ("RS", "RS"),
                            ("RO", "RO"),
                            ("RR", "RR"),
                            ("SC", "SC"),
                            ("SP", "SP"),
                            ("SE", "SE"),
                            ("TO", "TO"),
                        ],
                        max_length=2,
                        verbose_name="UF",
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="telefone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="e-mail"
                    ),
                ),
                ("site", models.URLField(blank=True, verbose_name="site")),
                (
                    "inicio_contrato",
                    models.DateField(
                        blank=True, null=True, verbose_name="inicio do contrato"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="observacoes"),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="empresas_responsavel",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="responsavel interno",
                    ),
                ),
            ],
            options={
                "verbose_name": "empresa",
                "verbose_name_plural": "empresas",
                "ordering": ["razao_social"],
            },
        ),
        migrations.CreateModel(
            name="Contato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                ("nome", models.CharField(max_length=150, verbose_name="nome")),
                (
                    "cargo",
                    models.CharField(blank=True, max_length=120, verbose_name="cargo"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="e-mail"
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="telefone"
                    ),
                ),
                (
                    "principal",
                    models.BooleanField(
                        default=False, verbose_name="contato principal"
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contatos",
                        to="empresas.empresa",
                        verbose_name="empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "contato",
                "verbose_name_plural": "contatos",
                "ordering": ["-principal", "nome"],
            },
        ),
    ]
