# Generated by Django 5.2.6 on 2026-09-22 14:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("empresas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "razao_social",
                    models.CharField(max_length=200, verbose_name="razao social"),
                ),
                (
                    "nome_fantasia",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="nome fantasia"
                    ),
                ),
                (
                    "cnpj",
                    models.CharField(blank=True, max_length=18, verbose_name="CNPJ"),
                ),
                (
                    "porte",
                    models.CharField(
                        choices=[
                            ("MEI", "MEI"),
                            ("ME", "Microempresa"),
                            ("EPP", "Empresa de pequeno porte"),
                            ("MEDIA", "Media empresa"),
                            ("GRANDE", "Grande empresa"),
                        ],
                        default="EPP",
                        max_length=10,
                        verbose_name="porte",
                    ),
                ),
                (
                    "setor",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="setor de atuacao"
                    ),
                ),
                (
                    "cidade",
                    models.CharField(blank=True, max_length=100, verbose_name="cidade"),
                ),
                (
                    "uf",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AC", "AC"),
                            ("AL", "AL"),
                            ("AP", "AP"),
                            ("AM", "AM"),
                            ("BA", "BA"),
                            ("CE", "CE"),
                            ("DF", "DF"),
                            ("ES", "ES"),
                            ("GO", "GO"),
                            ("MA", "MA"),
                            ("MT", "MT"),
                            ("MS", "MS"),
                            ("MG", "MG"),
                            ("PA", "PA"),
                            ("PB", "PB"),
                            ("PR", "PR"),
                            ("PE", "PE"),
                            ("PI", "PI"),
                            ("RJ", "RJ"),
                            ("RN", "RN"),
                            ("RS", "RS"),
                            ("RO", "RO"),
                            ("RR", "RR"),
                            ("SC", "SC"),
                            ("SP", "SP"),
                            ("SE", "SE"),
                            ("TO", "TO"),
                        ],
                        max_length=2,
                        verbose_name="UF",
                    ),
                ),
                (
                    "contato_nome",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="contato"
                    ),
                ),
                (
                    "contato_cargo",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="cargo do contato"
                    ),
                ),
                (
                    "contato_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="e-mail"
                    ),
                ),
                (
                    "contato_telefone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="telefone"
                    ),
                ),
                (
                    "origem",
                    models.CharField(
                        choices=[
                            ("IND", "Indicacao"),
                            ("SITE", "Site / formulario"),
                            ("EVEN", "Evento"),
                            ("ATIV", "Prospeccao ativa"),
                            ("PARC", "Escritorio parceiro"),
                            ("PUBL", "Publicacao judicial / DJE"),
                            ("OUT", "Outro"),
                        ],
                        default="ATIV",
                        max_length=4,
                        verbose_name="origem",
                    ),
                ),
                (
                    "situacao_juridica",
                    models.CharField(
                        choices=[
                            ("PRE", "Dificuldade financeira, sem processo"),
                            ("EXTRA", "Negociacao extrajudicial"),
                            ("RJ", "Recuperacao judicial em curso"),
                            ("RJENC", "Recuperacao judicial encerrada"),
                            ("FAL", "Falencia"),
                            ("OUT", "Outro"),
                        ],
                        default="PRE",
                        max_length=5,
                        verbose_name="situacao juridica",
                    ),
                ),
                (
                    "estagio",
                    models.CharField(
                        choices=[
                            ("NOVO", "Novo lead"),
                            ("CONT", "Contato iniciado"),
                            ("DIAG", "Diagnostico"),
                            ("PROP", "Proposta enviada"),
                            ("NEG", "Negociacao"),
                            ("GANHO", "Fechado - ganho"),
                            ("PERD", "Fechado - perdido"),
                        ],
                        default="NOVO",
                        max_length=5,
                        verbose_name="estagio",
                    ),
                ),
                (
                    "valor_estimado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="valor estimado do contrato",
                    ),
                ),
                (
                    "proximo_contato",
                    models.DateField(
                        blank=True, null=True, verbose_name="proximo contato"
                    ),
                ),
                (
                    "motivo_perda",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="motivo da perda"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="observacoes"),
                ),
                (
                    "empresa",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lead",
                        to="empresas.empresa",
                        verbose_name="empresa convertida",
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="responsavel",
                    ),
                ),
            ],
            options={
                "verbose_name": "lead",
                "verbose_name_plural": "leads",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="Atividade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("LIG", "Ligacao"),
                            ("MAIL", "E-mail"),
                            ("WPP", "WhatsApp"),
                            ("REUN", "Reuniao"),
                            ("VIS", "Visita"),
                            ("NOTA", "Anotacao"),
                        ],
                        default="LIG",
                        max_length=4,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "data",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="data"
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="titulo")),
                ("descricao", models.TextField(blank=True, verbose_name="descricao")),
                (
                    "autor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="atividades",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="autor",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="atividades",
                        to="crm.lead",
                        verbose_name="lead",
                    ),
                ),
            ],
            options={
                "verbose_name": "atividade",
                "verbose_name_plural": "atividades",
                "ordering": ["-data", "-id"],
            },
        ),
    ]
