# Generated by Django 5.2.6 on 2026-09-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="urgencia",
            field=models.CharField(
                choices=[
                    ("ALTA", "Urgencia alta"),
                    ("MEDIA", "Urgencia media"),
                    ("BAIXA", "Urgencia baixa"),
                    ("NA", "Nao avaliada"),
                ],
                default="NA",
                help_text="Vem do diagnostico feito no site, quando houver.",
                max_length=5,
                verbose_name="urgencia",
            ),
        ),
    ]
