# Generated by Django 5.2.6 on 2026-09-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_lead_urgencia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="urgencia",
            field=models.CharField(
                choices=[
                    ("ALTA", "Urgência alta"),
                    ("MEDIA", "Urgência média"),
                    ("BAIXA", "Urgência baixa"),
                    ("NA", "Não avaliada"),
                ],
                default="NA",
                help_text="Vem do diagnostico feito no site, quando houver.",
                max_length=5,
                verbose_name="urgencia",
            ),
        ),
    ]
