# Generated by Django 5.2.6 on 2026-09-22 16:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("processos", "0002_andamento_codigo_movimento_andamento_id_externo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvisoPrazo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "destinatario",
                    models.EmailField(max_length=254, verbose_name="destinatario"),
                ),
                (
                    "data",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="data do aviso",
                    ),
                ),
                (
                    "enviado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="enviado em"),
                ),
                (
                    "prazo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avisos",
                        to="processos.prazo",
                        verbose_name="prazo",
                    ),
                ),
            ],
            options={
                "verbose_name": "aviso de prazo",
                "verbose_name_plural": "avisos de prazo",
                "ordering": ["-enviado_em"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("prazo", "destinatario", "data"),
                        name="aviso_unico_por_dia",
                    )
                ],
            },
        ),
    ]
