# Generated by Django 5.2.6 on 2026-09-22 19:18

import apps.relacionamento.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("processos", "0004_credor_estagio_negociacao_credor_valor_negociado_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentoSolicitado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="documento")),
                (
                    "motivo",
                    models.CharField(
                        blank=True,
                        help_text="Explique em uma linha por que ele e necessario.",
                        max_length=250,
                        verbose_name="para que serve",
                    ),
                ),
                (
                    "prazo",
                    models.DateField(blank=True, null=True, verbose_name="prazo"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SOL", "Solicitado"),
                            ("REC", "Recebido, em conferencia"),
                            ("VAL", "Validado"),
                            ("RECU", "Precisa reenviar"),
                        ],
                        default="SOL",
                        max_length=4,
                        verbose_name="status",
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        blank=True,
                        upload_to=apps.relacionamento.models.caminho_documento_cliente,
                        verbose_name="arquivo enviado",
                    ),
                ),
                (
                    "enviado_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="enviado em"
                    ),
                ),
                (
                    "observacao_equipe",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="observacao da equipe"
                    ),
                ),
                (
                    "processo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitacoes",
                        to="processos.processorj",
                        verbose_name="processo",
                    ),
                ),
                (
                    "solicitado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documentos_solicitados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="solicitado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "documento solicitado",
                "verbose_name_plural": "documentos solicitados",
                "ordering": ["status", "prazo", "-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="Mensagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                ("texto", models.TextField(verbose_name="mensagem")),
                (
                    "lida_em",
                    models.DateTimeField(blank=True, null=True, verbose_name="lida em"),
                ),
                (
                    "autor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mensagens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="autor",
                    ),
                ),
                (
                    "processo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensagens",
                        to="processos.processorj",
                        verbose_name="processo",
                    ),
                ),
            ],
            options={
                "verbose_name": "mensagem",
                "verbose_name_plural": "mensagens",
                "ordering": ["criado_em"],
            },
        ),
        migrations.CreateModel(
            name="Reuniao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="assunto")),
                ("quando", models.DateTimeField(verbose_name="data e hora")),
                (
                    "duracao_minutos",
                    models.PositiveIntegerField(
                        default=60, verbose_name="duracao (min)"
                    ),
                ),
                (
                    "local",
                    models.CharField(
                        blank=True,
                        help_text="Endereco, sala ou o link da chamada.",
                        max_length=250,
                        verbose_name="local ou link",
                    ),
                ),
                (
                    "participantes",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="participantes"
                    ),
                ),
                ("pauta", models.TextField(blank=True, verbose_name="pauta")),
                (
                    "ata",
                    models.TextField(
                        blank=True, verbose_name="resumo do que foi decidido"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AGEN", "Agendada"),
                            ("REAL", "Realizada"),
                            ("CANC", "Cancelada"),
                        ],
                        default="AGEN",
                        max_length=4,
                        verbose_name="status",
                    ),
                ),
                (
                    "visivel_cliente",
                    models.BooleanField(default=True, verbose_name="visivel no portal"),
                ),
                (
                    "processo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reunioes",
                        to="processos.processorj",
                        verbose_name="processo",
                    ),
                ),
            ],
            options={
                "verbose_name": "reuniao",
                "verbose_name_plural": "reunioes",
                "ordering": ["-quando"],
            },
        ),
    ]
