# Generated by Django 5.2.6 on 2026-09-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relacionamento", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reuniao",
            options={
                "ordering": ["-quando"],
                "verbose_name": "reunião",
                "verbose_name_plural": "reuniões",
            },
        ),
        migrations.AlterField(
            model_name="documentosolicitado",
            name="status",
            field=models.CharField(
                choices=[
                    ("SOL", "Solicitado"),
                    ("REC", "Recebido, em conferência"),
                    ("VAL", "Validado"),
                    ("RECU", "Precisa reenviar"),
                ],
                default="SOL",
                max_length=4,
                verbose_name="status",
            ),
        ),
    ]
